[package]
name = "private_key_generator"
version = "0.1.0-pre.0"
edition = "2021"
rust-version = "1.73"
description = "Private key generator, based on HKDF"
readme = "README.md"
keywords = [
    "crypto",
    "KDF"
]
categories = [
    "cryptography",
    "no-std"
]
license = "MIT OR Apache-2.0"

[lib]
doctest = false # need to change this before publishing

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20 = { git = "https://github.com/nstilt1/stream-ciphers-rng.git", branch = "production", default-features = false, package = "chacha20", features = ["rng"] }
ecdsa = { version = "0.16.9", features = ["signing"]}
elliptic-curve = { version = "0.13.8", features = ["ecdh", "jwk", "pem", "pkcs8"] }
hkdf = "0.12.4"
secrecy = { version = "0.8", optional = true }
subtle = "2"
tracing = { version = "0.1.40", optional = true }
zeroize = { version = "1", optional = true }
 
[dev-dependencies]
blake2 = "0.10.6"
mock_instant = "0.6.0"
p384 = { version = "0.13.1", features = ["jwk"] }
rand = "0.10"
sha2 = "0.10.8"
trybuild = "1"

[features]
default = ["std"]
logging = ["tracing"]
std = [] # std is required for checking timestamps against UNIX_EPOCH
zeroize = ["dep:zeroize"]