[package]
name = "init_boxed"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
alloc = []

[dependencies]
zeroize = "1.7.0"
